//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORMACION
    {
        public int IDINFORMACION { get; set; }
        public string ANTECEDENTES { get; set; }
        public string MISION { get; set; }
        public string VISION { get; set; }
        public string OBJETIVO { get; set; }
    }
}
