//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_SEPLAN
    {
        public int IDNOTICIA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string TITULO { get; set; }
        public string ENCABEZADO { get; set; }
        public Nullable<System.DateTime> FECHAPUBLIC { get; set; }
        public string RESPONSABLE { get; set; }
        public string BALAZO1 { get; set; }
        public string BALAZO2 { get; set; }
        public string BALAZO3 { get; set; }
        public string VER_COPLADENAY { get; set; }
        public string VER_SEPLAN { get; set; }
        public string VER_INTRANET { get; set; }
        public string LUGAR { get; set; }
        public Nullable<decimal> PRIORIDAD { get; set; }
        public string SOLO_MEDIOS { get; set; }
        public string PARTICIPANTES { get; set; }
        public string RESENIA { get; set; }
        public byte[] FOTO_PRINCIPAL { get; set; }
        public string PIE_FOTO_PRINCIPAL { get; set; }
        public byte[] FOTO_2 { get; set; }
        public string PIE_FOTO_2 { get; set; }
        public byte[] FOTO_3 { get; set; }
        public string PIE_FOTO_3 { get; set; }
        public byte[] FOTO_4 { get; set; }
        public string PIE_FOTO_4 { get; set; }
        public byte[] FOTO_5 { get; set; }
        public string PIE_FOTO_5 { get; set; }
        public byte[] FOTO_6 { get; set; }
        public string PIE_FOTO_6 { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
    }
}
