//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_SEPLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTICIAS_SEPLAN()
        {
            this.BALAZO = new HashSet<BALAZO>();
        }
    
        public int IDNOTICIA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string TITULO { get; set; }
        public string CONTENIDO { get; set; }
        public Nullable<System.DateTime> FECHAPUBLIC { get; set; }
        public string LUGAR { get; set; }
        public string PARTICIPANTES { get; set; }
        public Nullable<bool> VER_COPLADENAY { get; set; }
        public Nullable<bool> VER_SEPLAN { get; set; }
        public Nullable<bool> VER_INTRANET { get; set; }
        public Nullable<bool> SOLO_MEDIOS { get; set; }
        public Nullable<byte> PRIORIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALAZO> BALAZO { get; set; }
        public virtual FOTOS FOTOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
