//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOTICIAS_SEPLAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NOTICIAS_SEPLAN()
        {
            this.BALAZO = new HashSet<BALAZO>();
            this.FOTOS = new HashSet<FOTOS>();
        }
    
        public int IDNOTICIA { get; set; }
        public Nullable<int> IDUSUARIO { get; set; }
        public string TITULO { get; set; }
        public string CONTENIDO { get; set; }
        public System.DateTime FECHACAPTURA { get; set; }
        public System.DateTime FECHAPUBLIC { get; set; }
        public string LUGAR { get; set; }
        public byte PRIORIDAD { get; set; }
        public string ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BALAZO> BALAZO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FOTOS> FOTOS { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
