
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace siteSPPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ORGANIGRAMA
{

    public int IDORGANIGRAMA { get; set; }

    public Nullable<int> IDUSUARIO { get; set; }

    public byte[] IMAGEN { get; set; }

    public Nullable<System.DateTime> FECHACREACION { get; set; }

    public string ESTATUS { get; set; }



    public virtual USUARIO USUARIO { get; set; }

}

}
