
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace siteSPPP.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TIPO_PLANTILLA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TIPO_PLANTILLA()
    {

        this.PLANTILLA = new HashSet<PLANTILLA>();

        this.ARCHIVOS = new HashSet<ARCHIVOS>();

    }


    public int IDTIPO { get; set; }

    public string TIPOPLANTILLA { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PLANTILLA> PLANTILLA { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ARCHIVOS> ARCHIVOS { get; set; }

}

}
