//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.NOTICIAS_SEPLAN = new HashSet<NOTICIAS_SEPLAN>();
        }
    
        public int IDUSUARIO { get; set; }
        public string USUARIOINICIA { get; set; }
        public string CONTRASENA { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public Nullable<byte> ROL { get; set; }
        public string ESTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTICIAS_SEPLAN> NOTICIAS_SEPLAN { get; set; }
    }
}
