//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace siteSPPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIO()
        {
            this.INFORMES = new HashSet<INFORMES>();
            this.NOTICIAS = new HashSet<NOTICIAS_SEPLAN>();
            this.PLANTILLA = new HashSet<PLANTILLA>();
            this.SERVIDORESPUBLICOS = new HashSet<SERVIDORESPUBLICOS>();
        }
    
        public int IDUSUARIO { get; set; }
        public string USUARIOINICIA { get; set; }
        public string CONTRASENA { get; set; }
        public string NOMBREUSUARIO { get; set; }
        public byte ROL { get; set; }
        public string ESTATUS { get; set; }
        public System.DateTime FECHAREGISTRO { get; set; }
        public string CORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INFORMES> INFORMES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NOTICIAS_SEPLAN> NOTICIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PLANTILLA> PLANTILLA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SERVIDORESPUBLICOS> SERVIDORESPUBLICOS { get; set; }
    }
}
